Common:
  XRayEnabled: false
  EcsCapacityProviderFargateWeight: 0
  EcsCapacityProviderFargateSpotWeight: 1
EcsCluster:
  ContainerInsightsEnabled: true
EventFirehose:
  BufferingIntervalSeconds: 60
  BufferingSizeMiB: 5
  DataOutputExpirationDays: 1
  ErrorOutputExpirationDays: 14
GremlinCsv:
  ExpirationDays: 2
GremlinCsvConverter:
  LambdaTimeoutSeconds: 60
GremlinCsvLoader:
  Enabled: true
  MemoryLimitMiB: 512
  Cpu: 256
Neptune:
  InstanceType: 'db.t3.medium'
  # InstanceType: 'db.r5.large'
NeptuneNotebook:
  InstanceType: 'ml.t3.medium'
  PersistentDirectory: 'Persistent'
NeptuneNotebookEfs:
  Encrypted: false
  EnableAutomaticBackups: false
Tweets:
  S3PathPrefix: 'tweets'
TweetsProducer:
  Enabled: true
  Filter: 'aws'
  MemoryLimitMiB: 512
  Cpu: 256
TwitterApi:
  ConsumerKeySsmParameter: '/twitter-api/consumer-key'
  ConsumerSecretSsmParameter: '/twitter-api/consumer-secret'
  AccessTokenSsmParameter: '/twitter-api/access-token'
  AccessTokenSecretSsmParameter: '/twitter-api/access-token-secret'
Vpc:
  CidrRange: '10.42.0.0/16'
  MaxAZs: 2
  NatGateways: 1
  UseNatInstances: true
WikimediaEvents:
  S3PathPrefix: 'wikimedia-events'
WikimediaEventsProducer:
  Enabled: false
  WikiRegex: 'enwiki'
  MemoryLimitMiB: 512
  Cpu: 256